const LANG_KEY = "gugudan-language";
const legalLanguageSelect = document.getElementById("legalLanguageSelect");
const page = document.body.dataset.page;

const I18N = {
  ko: {
    languageLabel: "언어",
    linkHome: "홈",
    linkAbout: "사이트 소개",
    linkPrivacy: "개인정보처리방침",
    linkContact: "문의하기",
    linkQuizStart: "퀴즈 시작",
    linkGuide: "학습 가이드",
    linkTerms: "이용약관",

    aboutTitleTag: "사이트 소개 | 구구단 퀴즈 놀이터",
    aboutMeta: "구구단 퀴즈 놀이터 서비스 소개 페이지",
    aboutBadge: "사이트 정보",
    aboutH1: "구구단 퀴즈 놀이터 소개",
    aboutLead: "구구단 퀴즈 놀이터는 기초 연산을 쉽고 재미있게 연습할 수 있도록 만든 웹 학습 서비스입니다.",
    aboutSectionOverview: "서비스 개요",
    aboutOverviewP1: "2단부터 9단까지(확장 시 20단) 원하는 단을 반복해서 연습할 수 있습니다.",
    aboutOverviewP2: "정답률, 자주 틀리는 문제, 답변 속도를 바탕으로 학습에 도움이 되는 피드백을 제공합니다.",
    aboutSectionOps: "운영 정보",
    aboutOps1: "운영 형태: 개인 운영 학습 사이트",
    aboutOps2: "서비스 성격: 무료 교육/학습 콘텐츠",
    aboutOps3: "회원가입: 없음",
    aboutOps4: "최종 업데이트: 2026-02-27",
    aboutSectionPrinciples: "콘텐츠 운영 원칙",
    aboutPrinciple1: "학습자가 실제로 사용할 수 있는 문제 풀이 경험과 복습 동선을 우선으로 설계합니다.",
    aboutPrinciple2: "콘텐츠는 자동 복사나 무단 전재가 아닌, 직접 작성한 설명과 학습 가이드를 기반으로 운영합니다.",
    aboutPrinciple3: "사용자 신뢰를 위해 정책, 문의 채널, 운영 정보를 공개 페이지에서 상시 제공합니다.",
    aboutPrinciple4: "학습 서비스 목적에 맞지 않는 유해/불법 콘텐츠는 게시하지 않습니다.",
    aboutOperatorLabel: "운영자 문의",
    aboutSectionLinks: "바로가기",

    privacyTitleTag: "개인정보처리방침 | 구구단 퀴즈 놀이터",
    privacyMeta: "구구단 퀴즈 놀이터 개인정보처리방침",
    privacyBadge: "정책 문서",
    privacyH1: "개인정보처리방침",
    privacyLead: "필요한 최소한의 정보만 사용하며, 학습 기록은 사용자의 브라우저에 저장됩니다.",
    privacySectionStore: "1. 수집/저장되는 정보",
    privacyStoreIntro: "회원가입 없이 이용할 수 있으며, 이름·이메일처럼 개인을 직접 식별할 수 있는 정보는 자체 서버에 저장하지 않습니다.",
    privacyStore1: "브라우저 로컬 저장소(localStorage) 학습 기록: gugudan-history-v1",
    privacyStore2: "언어 설정: gugudan-language",
    privacyStore3: "TTS 음성 선택값: gugudan-voice-*",
    privacySectionUse: "2. 정보 사용 목적",
    privacyUse1: "학습 이력, 정답률, 오답 패턴 표시",
    privacyUse2: "선택 언어 및 음성 설정 유지",
    privacyUse3: "사용자 경험 개선을 위한 기능 제공",
    privacySectionAds: "3. 제3자 서비스 및 쿠키",
    privacyAdsIntro: "광고 제공을 위해 Google AdSense를 사용할 수 있으며, Google은 광고 제공 과정에서 쿠키를 사용할 수 있습니다.",
    privacyAds1: "광고는 상황에 따라 개인 맞춤 광고 또는 비개인화 광고 형태로 제공될 수 있습니다.",
    privacyAds2: "Google의 광고 쿠키는 광고 게재, 빈도 제한, 성과 측정에 사용될 수 있습니다.",
    privacyAds3: "사용자는 Google 광고 설정 페이지에서 광고 개인화를 직접 제어할 수 있습니다.",
    privacyGoogleAds: "Google 광고 쿠키 정책",
    privacyGooglePrivacy: "Google 개인정보처리방침",
    privacyGoogleSettings: "Google 광고 설정",
    privacySectionDelete: "4. 보관 기간 및 삭제",
    privacyDelete1: "사이트 내 \"기록 삭제\" 버튼으로 삭제할 수 있습니다.",
    privacyDelete2: "브라우저의 사이트 데이터/쿠키 삭제 기능으로도 삭제할 수 있습니다.",
    privacySectionChild: "5. 아동 관련 안내",
    privacyChildBody: "본 사이트는 기초 학습 콘텐츠를 제공할 수 있습니다. 보호자는 아동의 인터넷 사용 및 광고 노출 정책을 함께 확인해 주세요.",
    privacyChild1: "보호자는 자녀의 기기에서 광고 개인화, 쿠키 및 추적 설정을 점검해 주세요.",
    privacyChild2: "아동 대상 환경에서는 비개인화 광고 설정을 우선 검토하는 것을 권장합니다.",
    privacySectionSecurity: "6. 사이트 접근 로그 및 보안",
    privacySecurityP1:
      "본 사이트는 정적 웹사이트로 운영되며, 별도의 회원 DB를 보유하지 않습니다. 다만 GitHub Pages, 브라우저, 광고 네트워크 등 인프라 제공자 측에서 기술적 로그가 처리될 수 있습니다.",
    privacySecurityP2:
      "서비스 안정성 확보를 위해 브라우저 보안 정책(HTTPS, 최신 브라우저 권장)을 따르며, 정책 위반 또는 악성 행위가 발견될 경우 접근이 제한될 수 있습니다.",
    privacySectionChange: "7. 정책 변경",
    privacyChangeBody: "정책이 변경될 경우 본 페이지에서 고지합니다.",
    privacyEffectiveDate: "시행일: 2026-02-27",
    privacyUpdatedOn: "최종 수정일: 2026-02-27",

    contactTitleTag: "문의하기 | 구구단 퀴즈 놀이터",
    contactMeta: "구구단 퀴즈 놀이터 문의 안내",
    contactBadge: "고객 지원",
    contactH1: "문의하기",
    contactLead: "이용 중 불편사항, 버그, 정책 관련 문의는 아래 채널로 보내주세요.",
    contactSectionChannel: "문의 채널",
    contactChannelBody: "문의는 아래 이메일로 접수하고 있습니다.",
    contactSendEmail: "이메일 보내기",
    contactEmailLabel: "이메일",
    contactResponse: "영업일 기준 2~3일 내 답변드리는 것을 목표로 합니다.",
    contactSectionInfo: "빠른 확인을 위한 정보",
    contactInfo1: "발생한 문제의 화면 또는 재현 순서",
    contactInfo2: "사용 기기/브라우저(예: iPhone Safari, Chrome)",
    contactInfo3: "문제가 발생한 날짜와 시간",
    contactInfo4: "선택한 설정값(언어, 단, 모드, 문제 수 등)",
    contactSectionOperator: "운영자 확인 정보",
    contactOperator1: "서비스명: 구구단 퀴즈 놀이터 (Times Table Quiz Playground)",
    contactOperator2: "운영 목적: 무료 교육/학습 콘텐츠 제공",
    contactOperator3: "문의 접수: 이메일 1:1 응대",
    contactOperatorPolicyLabel: "정책 문서:",
    contactSectionScope: "처리 범위",
    contactScope1: "기능 오류 및 성능 문제",
    contactScope2: "광고 표시 관련 문의",
    contactScope3: "정책 및 데이터 처리 관련 문의",

    guideTitleTag: "학습 가이드 | 구구단 퀴즈 놀이터",
    guideMeta: "구구단 암기 효율을 높이는 일일 학습 루틴, 오답 복습 전략, 부모·교사 운영 팁 안내",
    guideBadge: "학습 자료",
    guideH1: "구구단 학습 가이드",
    guideLead: "구구단 퀴즈 놀이터를 가장 효과적으로 사용하는 방법을 정리한 운영 가이드입니다.",
    guideSection1Title: "1. 권장 학습 루틴",
    guideSection1P1:
      "구구단 학습은 한 번에 오래 하는 것보다 짧고 자주 반복하는 것이 좋습니다. 권장 루틴은 하루 10~15분, 주 5회입니다. 처음에는 2~5단 중심으로 정확도를 높이고, 정답률이 안정되면 6~9단으로 확장하는 방식이 효율적입니다.",
    guideSection1Item1: "1주차: 2~4단 중심, 정답률 80% 목표",
    guideSection1Item2: "2주차: 5~7단 추가, 정답률 85% 목표",
    guideSection1Item3: "3주차: 8~9단 포함 전체 학습, 정답률 88% 목표",
    guideSection1Item4: "4주차: 오답 집중 + 챌린지 모드로 속도 강화",
    guideSection2Title: "2. 모드별 활용 전략",
    guideSection2Mode1Title: "기본 모드",
    guideSection2Mode1Body: "새로운 단을 익히거나 정확도를 먼저 확보할 때 사용하세요. 목표는 빠른 속도보다 오답 감소입니다.",
    guideSection2Mode2Title: "오답 집중 모드",
    guideSection2Mode2Body: "기록된 틀린 문제를 다시 푸는 모드입니다. 짧은 시간에 취약 문제를 보완할 때 가장 효과적입니다.",
    guideSection2Mode3Title: "챌린지 모드",
    guideSection2Mode3Body:
      "제한 시간 내에 답하는 훈련으로, 실전 계산 속도를 키우는 데 유리합니다. 처음에는 4~5초, 익숙해지면 3초, 이후 2초로 단계적으로 낮추세요.",
    guideSection3Title: "3. 부모/교사를 위한 운영 팁",
    guideSection3Item1: "학습 후 결과 화면에서 틀린 문제 보기를 함께 확인해 피드백 대화를 진행하세요.",
    guideSection3Item2: "정답률이 떨어지는 날이 있어도 총 학습 횟수와 추세를 기준으로 평가하는 것이 중요합니다.",
    guideSection3Item3: "기록 삭제는 재시작 용도로만 사용하고, 기본적으로는 데이터를 누적해 성장 곡선을 보세요.",
    guideSection3Item4: "주 1회는 쉬운 단만 빠르게 풀어 성취감을 유지하는 세션을 포함하는 것이 좋습니다.",
    guideSection4Title: "4. 자주 묻는 질문(FAQ)",
    guideFaq1Q: "Q. 하루에 얼마나 연습해야 하나요?",
    guideFaq1A: "A. 초등 저학년 기준 하루 10~15분, 주 5회가 가장 무리가 적고 효과적입니다.",
    guideFaq2Q: "Q. 오답이 너무 많으면 어떻게 시작하나요?",
    guideFaq2A: "A. 문제 수를 20개로 줄이고, 2~4단만 선택해 기본 모드로 2~3회 진행한 뒤 오답 집중 모드로 넘어가세요.",
    guideFaq3Q: "Q. 광고가 학습에 방해될 때는 어떻게 하나요?",
    guideFaq3A: "A. 학습 방해 광고나 부적절 광고가 보이면 문의 페이지로 알려주시면 검토 후 조치합니다.",
    guideSection5Title: "5. 관련 문서",
    guideUpdatedOn: "최종 수정일: 2026-02-27",

    termsTitleTag: "이용약관 | 구구단 퀴즈 놀이터",
    termsMeta: "구구단 퀴즈 놀이터 서비스 이용 규칙, 광고 정책, 책임 제한, 정책 변경 절차 안내",
    termsBadge: "약관",
    termsH1: "이용약관",
    termsLead: "구구단 퀴즈 놀이터 서비스 이용에 필요한 기본 규칙과 책임 범위를 안내합니다.",
    termsSection1Title: "1. 서비스 목적",
    termsSection1Body: "구구단 퀴즈 놀이터는 학습자를 위한 무료 교육 콘텐츠를 제공합니다. 본 서비스는 구구단 학습의 반복 훈련, 오답 복습, 학습 이력 확인을 돕기 위해 운영됩니다.",
    termsSection2Title: "2. 이용 조건",
    termsSection2Item1: "서비스는 별도 회원가입 없이 이용할 수 있습니다.",
    termsSection2Item2: "학습 기록은 사용자 브라우저의 localStorage에 저장됩니다.",
    termsSection2Item3: "서비스 기능, UI, 콘텐츠는 운영 정책에 따라 변경될 수 있습니다.",
    termsSection2Item4: "서비스 안정성 유지를 위해 비정상적인 자동 접근은 제한될 수 있습니다.",
    termsSection3Title: "3. 금지 행위",
    termsSection3Item1: "서비스 운영을 방해하는 트래픽 유발, 악성 스크립트 실행",
    termsSection3Item2: "사이트 콘텐츠 무단 복제·재배포 또는 출처 없는 재게시",
    termsSection3Item3: "타인의 권리를 침해하거나 불법적인 목적으로 서비스 이용",
    termsSection3Item4: "광고 클릭 유도, 부정 클릭 등 광고 정책 위반 행위",
    termsSection4Title: "4. 광고 및 외부 서비스",
    termsSection4Body1Prefix: "본 사이트는 운영 비용 충당을 위해 Google AdSense 광고를 사용할 수 있습니다. 광고 표시와 관련된 쿠키 및 기술은 Google 정책을 따르며, 자세한 내용은",
    termsSection4Body1Suffix: "에서 확인할 수 있습니다.",
    termsSection4Body2: "외부 링크(예: Google 정책 페이지)로 이동한 이후의 서비스는 각 사이트의 약관과 정책이 적용됩니다.",
    termsSection5Title: "5. 책임 제한",
    termsSection5Item1: "본 서비스는 교육 보조 도구이며, 학업 성취를 법적으로 보증하지 않습니다.",
    termsSection5Item2: "브라우저·기기 환경 차이로 일부 기능이 제한될 수 있습니다.",
    termsSection5Item3: "운영자는 천재지변, 네트워크 장애, 외부 플랫폼 이슈로 인한 중단에 대해 책임을 제한할 수 있습니다.",
    termsSection6Title: "6. 약관 변경",
    termsSection6Body: "약관은 법령 변경, 서비스 운영 정책 변경 시 수정될 수 있으며, 변경 시 본 페이지에 공지합니다. 중대한 변경의 경우 사전 안내를 원칙으로 합니다.",
    termsSection7Title: "7. 문의",
    termsSection7Body: "약관 관련 문의는 아래 이메일로 접수할 수 있습니다.",
    termsContactPage: "문의 페이지",
    termsEffectiveDate: "시행일: 2026-02-27",
  },

  en: {
    languageLabel: "Language",
    linkHome: "Home",
    linkAbout: "About",
    linkPrivacy: "Privacy Policy",
    linkContact: "Contact",
    linkQuizStart: "Start Quiz",
    linkGuide: "Learning Guide",
    linkTerms: "Terms",

    aboutTitleTag: "About | Times Table Quiz Playground",
    aboutMeta: "About page for Times Table Quiz Playground",
    aboutBadge: "Site Info",
    aboutH1: "About Times Table Quiz Playground",
    aboutLead: "Times Table Quiz Playground is a web learning service that helps learners practice basic multiplication in a fun, simple way.",
    aboutSectionOverview: "Service Overview",
    aboutOverviewP1: "You can repeatedly practice selected tables from 2 to 9 (or up to 20 when extension is enabled).",
    aboutOverviewP2: "The site provides learning feedback based on accuracy, frequently missed questions, and response speed.",
    aboutSectionOps: "Operations",
    aboutOps1: "Operation type: Individually operated learning site",
    aboutOps2: "Service type: Free educational content",
    aboutOps3: "Account registration: Not required",
    aboutOps4: "Last updated: 2026-02-27",
    aboutSectionPrinciples: "Content Principles",
    aboutPrinciple1: "We prioritize practical question-solving flow and review paths that learners can actually use.",
    aboutPrinciple2: "Content is operated with original explanations and guides, not automated copying or unauthorized reposting.",
    aboutPrinciple3: "To maintain trust, policy pages, contact channels, and operating information are always visible.",
    aboutPrinciple4: "We do not publish harmful or illegal content unrelated to educational goals.",
    aboutOperatorLabel: "Operator Contact",
    aboutSectionLinks: "Quick Links",

    privacyTitleTag: "Privacy Policy | Times Table Quiz Playground",
    privacyMeta: "Privacy policy for Times Table Quiz Playground",
    privacyBadge: "Policy",
    privacyH1: "Privacy Policy",
    privacyLead: "We use only the minimum data needed, and study history is stored in your browser.",
    privacySectionStore: "1. What We Store",
    privacyStoreIntro: "The site can be used without sign-up and does not store directly identifiable personal information (such as name or email) on our own servers.",
    privacyStore1: "Study history in browser localStorage: gugudan-history-v1",
    privacyStore2: "Language preference: gugudan-language",
    privacyStore3: "TTS voice preference: gugudan-voice-*",
    privacySectionUse: "2. Why We Use It",
    privacyUse1: "To show study history, accuracy, and frequently missed questions",
    privacyUse2: "To keep your selected language and voice settings",
    privacyUse3: "To improve user experience",
    privacySectionAds: "3. Third-Party Services and Cookies",
    privacyAdsIntro: "This site may use Google AdSense for advertising, and Google may use cookies as part of ad delivery.",
    privacyAds1: "Ads may be served as personalized or non-personalized depending on context.",
    privacyAds2: "Google ad cookies may be used for ad delivery, frequency capping, and performance measurement.",
    privacyAds3: "Users can directly manage ad personalization via Google ad settings.",
    privacyGoogleAds: "Google Ads Cookies Policy",
    privacyGooglePrivacy: "Google Privacy Policy",
    privacyGoogleSettings: "Google Ad Settings",
    privacySectionDelete: "4. Retention and Deletion",
    privacyDelete1: "You can delete data using the \"Clear History\" button on this site.",
    privacyDelete2: "You can also delete data through your browser's site data/cookie settings.",
    privacySectionChild: "5. Child-Related Notice",
    privacyChildBody: "This site may provide basic learning content for children. Guardians should review internet and ad exposure settings together with children.",
    privacyChild1: "Guardians should review ad personalization, cookie, and tracking settings on their child's device.",
    privacyChild2: "In child-focused environments, we recommend reviewing non-personalized ad settings first.",
    privacySectionSecurity: "6. Access Logs and Security",
    privacySecurityP1:
      "This site is operated as a static website and does not maintain a separate member database. However, technical logs may be processed by infrastructure providers such as GitHub Pages, browsers, and ad networks.",
    privacySecurityP2:
      "For service stability, we follow browser security best practices (HTTPS, latest browser). Access may be limited if policy violations or malicious behavior are detected.",
    privacySectionChange: "7. Policy Changes",
    privacyChangeBody: "Any policy changes will be announced on this page.",
    privacyEffectiveDate: "Effective date: 2026-02-27",
    privacyUpdatedOn: "Last updated: 2026-02-27",

    contactTitleTag: "Contact | Times Table Quiz Playground",
    contactMeta: "Contact page for Times Table Quiz Playground",
    contactBadge: "Support",
    contactH1: "Contact",
    contactLead: "For usability issues, bugs, or policy questions, please contact us through the channel below.",
    contactSectionChannel: "Contact Channel",
    contactChannelBody: "Inquiries are accepted via the email address below.",
    contactSendEmail: "Send Email",
    contactEmailLabel: "Email",
    contactResponse: "Our target response time is within 2-3 business days.",
    contactSectionInfo: "Information That Helps",
    contactInfo1: "Screenshot or steps to reproduce the issue",
    contactInfo2: "Device/browser used (e.g., iPhone Safari, Chrome)",
    contactInfo3: "Date and time when the issue occurred",
    contactInfo4: "Selected settings (language, table, mode, question count, etc.)",
    contactSectionOperator: "Operator Information",
    contactOperator1: "Service name: Times Table Quiz Playground",
    contactOperator2: "Purpose: Free educational and learning content",
    contactOperator3: "Support channel: One-to-one email response",
    contactOperatorPolicyLabel: "Policy pages:",
    contactSectionScope: "Supported Topics",
    contactScope1: "Feature bugs and performance issues",
    contactScope2: "Questions about ad display",
    contactScope3: "Policy and data handling questions",

    guideTitleTag: "Learning Guide | Times Table Quiz Playground",
    guideMeta: "Daily routines, mistake-review strategy, and parent/teacher tips to improve multiplication learning",
    guideBadge: "Learning Resource",
    guideH1: "Times Table Learning Guide",
    guideLead: "This guide explains the most effective way to use Times Table Quiz Playground.",
    guideSection1Title: "1. Recommended Study Routine",
    guideSection1P1:
      "For multiplication practice, short and frequent sessions are better than long sessions. A recommended routine is 10-15 minutes a day, 5 days a week. Start with tables 2-5 for accuracy, then expand to 6-9 as stability improves.",
    guideSection1Item1: "Week 1: Focus on tables 2-4, target 80% accuracy",
    guideSection1Item2: "Week 2: Add tables 5-7, target 85% accuracy",
    guideSection1Item3: "Week 3: Include tables 8-9, target 88% accuracy",
    guideSection1Item4: "Week 4: Strengthen speed with Mistake Focus + Challenge mode",
    guideSection2Title: "2. How to Use Each Mode",
    guideSection2Mode1Title: "Normal Mode",
    guideSection2Mode1Body: "Use it when learning new tables or securing accuracy first. The goal is reducing mistakes before speed.",
    guideSection2Mode2Title: "Mistake Focus Mode",
    guideSection2Mode2Body: "This mode reuses previously missed questions. It is the most efficient way to fix weak points quickly.",
    guideSection2Mode3Title: "Challenge Mode",
    guideSection2Mode3Body:
      "Challenge mode trains fast recall under time pressure. Start with 4-5 seconds, then reduce to 3 seconds, and eventually 2 seconds.",
    guideSection3Title: "3. Tips for Parents and Teachers",
    guideSection3Item1: "After each session, review missed questions together and discuss why mistakes happened.",
    guideSection3Item2: "Evaluate progress by total sessions and trend, not by one bad day.",
    guideSection3Item3: "Use history reset only for restart scenarios; normally keep data to track growth.",
    guideSection3Item4: "Add one easy-confidence session per week to maintain motivation.",
    guideSection4Title: "4. Frequently Asked Questions",
    guideFaq1Q: "Q. How long should we practice each day?",
    guideFaq1A: "A. For younger learners, 10-15 minutes per day, 5 days a week, is usually the most sustainable and effective.",
    guideFaq2Q: "Q. What if there are too many mistakes?",
    guideFaq2A: "A. Reduce question count to 20, focus on tables 2-4 in Normal mode for 2-3 sessions, then move to Mistake Focus mode.",
    guideFaq3Q: "Q. What if ads interrupt learning?",
    guideFaq3A: "A. If you see distracting or inappropriate ads, contact us through the support page for review.",
    guideSection5Title: "5. Related Documents",
    guideUpdatedOn: "Last updated: 2026-02-27",

    termsTitleTag: "Terms | Times Table Quiz Playground",
    termsMeta: "Service rules, ad policy notice, liability limits, and revision process for Times Table Quiz Playground",
    termsBadge: "Terms",
    termsH1: "Terms of Service",
    termsLead: "This page explains the basic rules and responsibilities for using Times Table Quiz Playground.",
    termsSection1Title: "1. Service Purpose",
    termsSection1Body:
      "Times Table Quiz Playground provides free educational content for learners. The service is operated to support repeated multiplication practice, mistake review, and learning history tracking.",
    termsSection2Title: "2. Usage Conditions",
    termsSection2Item1: "The service can be used without account registration.",
    termsSection2Item2: "Learning records are stored in the user's browser localStorage.",
    termsSection2Item3: "Features, UI, and content may change according to operation policy.",
    termsSection2Item4: "Abnormal automated access may be restricted to keep service stable.",
    termsSection3Title: "3. Prohibited Activities",
    termsSection3Item1: "Traffic abuse or malicious scripts that interfere with operation",
    termsSection3Item2: "Unauthorized copying/reposting of site content without attribution",
    termsSection3Item3: "Using the service for illegal purposes or rights infringement",
    termsSection3Item4: "Ad-policy violations such as click inducement or invalid clicks",
    termsSection4Title: "4. Ads and External Services",
    termsSection4Body1Prefix:
      "This site may use Google AdSense to support operating costs. Ad-related cookies and technologies follow Google policy, and details are available in the",
    termsSection4Body1Suffix: "page.",
    termsSection4Body2: "Once you move to external links (for example, Google policy pages), the terms and policies of those sites apply.",
    termsSection5Title: "5. Limitation of Liability",
    termsSection5Item1: "This service is an educational aid and does not legally guarantee academic outcomes.",
    termsSection5Item2: "Some features may vary depending on browser and device environment.",
    termsSection5Item3: "The operator may limit liability for outages caused by force majeure, network failure, or external platform issues.",
    termsSection6Title: "6. Changes to Terms",
    termsSection6Body:
      "These terms may be revised due to legal changes or operational policy updates. Changes will be announced on this page, with prior notice for major updates.",
    termsSection7Title: "7. Contact",
    termsSection7Body: "Questions about these terms can be sent to the email address below.",
    termsContactPage: "Contact page",
    termsEffectiveDate: "Effective date: 2026-02-27",
  },

  zh: {
    languageLabel: "语言",
    linkHome: "首页",
    linkAbout: "网站介绍",
    linkPrivacy: "隐私政策",
    linkContact: "联系我们",
    linkQuizStart: "开始测验",
    linkGuide: "学习指南",
    linkTerms: "使用条款",

    aboutTitleTag: "网站介绍 | 九九乘法测验乐园",
    aboutMeta: "九九乘法测验乐园介绍页面",
    aboutBadge: "网站信息",
    aboutH1: "关于九九乘法测验乐园",
    aboutLead: "“九九乘法测验乐园”是一个帮助用户轻松、有趣地练习基础乘法的网页学习服务。",
    aboutSectionOverview: "服务概览",
    aboutOverviewP1: "可练习2到9乘法（开启扩展后可到20），并按所选乘法段反复练习。",
    aboutOverviewP2: "系统会根据正确率、常错题和挑战模式答题速度提供学习反馈。",
    aboutSectionOps: "运营信息",
    aboutOps1: "运营形式：个人运营学习网站",
    aboutOps2: "服务性质：免费教育内容",
    aboutOps3: "是否需要注册：不需要",
    aboutOps4: "最后更新：2026-02-27",
    aboutSectionLinks: "快捷入口",

    privacyTitleTag: "隐私政策 | 九九乘法测验乐园",
    privacyMeta: "九九乘法测验乐园隐私政策",
    privacyBadge: "政策文档",
    privacyH1: "隐私政策",
    privacyLead: "我们只使用必要的最少信息，学习记录保存在您的浏览器中。",
    privacySectionStore: "1. 收集/保存的信息",
    privacyStoreIntro: "本网站无需注册，不会在自有服务器保存姓名、邮箱等可直接识别个人身份的信息。",
    privacyStore1: "浏览器 localStorage 学习记录：gugudan-history-v1",
    privacyStore2: "语言设置：gugudan-language",
    privacyStore3: "TTS 语音设置：gugudan-voice-*",
    privacySectionUse: "2. 使用目的",
    privacyUse1: "显示学习记录、正确率和常错题",
    privacyUse2: "保留语言与语音设置",
    privacyUse3: "改善使用体验",
    privacySectionAds: "3. 第三方服务与 Cookie",
    privacyAdsIntro: "本网站可能使用 Google AdSense 提供广告，Google 可能在广告投放过程中使用 Cookie。",
    privacyGoogleAds: "Google 广告 Cookie 政策",
    privacyGooglePrivacy: "Google 隐私政策",
    privacySectionDelete: "4. 保存期限与删除",
    privacyDelete1: "可通过网站内“清除记录”按钮删除数据。",
    privacyDelete2: "也可通过浏览器站点数据/Cookie 删除功能删除。",
    privacySectionChild: "5. 儿童相关说明",
    privacyChildBody: "本网站可能提供基础学习内容。监护人请与儿童一起确认网络使用与广告设置。",
    privacySectionChange: "7. 政策变更",
    privacyChangeBody: "如有变更，将在本页面公告。",
    privacyEffectiveDate: "生效日期：2026-02-27",

    contactTitleTag: "联系我们 | 九九乘法测验乐园",
    contactMeta: "九九乘法测验乐园联系方式",
    contactBadge: "客户支持",
    contactH1: "联系我们",
    contactLead: "如遇到使用问题、错误或政策相关咨询，请通过下方渠道联系。",
    contactSectionChannel: "联系渠道",
    contactChannelBody: "咨询可通过以下邮箱提交。",
    contactSendEmail: "发送邮件",
    contactEmailLabel: "邮箱",
    contactResponse: "目标回复时间：2-3个工作日内。",
    contactSectionInfo: "有助于快速处理的信息",
    contactInfo1: "问题截图或复现步骤",
    contactInfo2: "使用设备/浏览器（例如 iPhone Safari、Chrome）",
    contactInfo3: "问题发生日期与时间",
    contactInfo4: "当时选择的设置（语言、乘法段、模式、题量等）",
    contactSectionScope: "受理范围",
    contactScope1: "功能错误与性能问题",
    contactScope2: "广告显示相关咨询",
    contactScope3: "政策与数据处理相关咨询",
  },

  ja: {
    languageLabel: "言語",
    linkHome: "ホーム",
    linkAbout: "サイト紹介",
    linkPrivacy: "プライバシーポリシー",
    linkContact: "お問い合わせ",
    linkQuizStart: "クイズ開始",
    linkGuide: "学習ガイド",
    linkTerms: "利用規約",

    aboutTitleTag: "サイト紹介 | 九九クイズ広場",
    aboutMeta: "九九クイズ広場の紹介ページ",
    aboutBadge: "サイト情報",
    aboutH1: "九九クイズ広場について",
    aboutLead: "九九クイズ広場は、基礎のかけ算を楽しく・手軽に練習できるWeb学習サービスです。",
    aboutSectionOverview: "サービス概要",
    aboutOverviewP1: "2〜9の段（拡張時は20まで）を、選んだ設定で繰り返し練習できます。",
    aboutOverviewP2: "正答率、よく間違える問題、チャレンジ時の解答スピードをもとに学習フィードバックを提供します。",
    aboutSectionOps: "運営情報",
    aboutOps1: "運営形態：個人運営の学習サイト",
    aboutOps2: "サービス種別：無料の教育コンテンツ",
    aboutOps3: "会員登録：不要",
    aboutOps4: "最終更新：2026-02-27",
    aboutSectionLinks: "リンク",

    privacyTitleTag: "プライバシーポリシー | 九九クイズ広場",
    privacyMeta: "九九クイズ広場のプライバシーポリシー",
    privacyBadge: "ポリシー",
    privacyH1: "プライバシーポリシー",
    privacyLead: "必要最小限の情報のみを扱い、学習履歴はお使いのブラウザに保存されます。",
    privacySectionStore: "1. 収集・保存される情報",
    privacyStoreIntro: "会員登録なしで利用でき、氏名・メールアドレスなど個人を直接特定できる情報は当サイトのサーバーに保存しません。",
    privacyStore1: "ブラウザ localStorage の学習履歴：gugudan-history-v1",
    privacyStore2: "言語設定：gugudan-language",
    privacyStore3: "TTS音声設定：gugudan-voice-*",
    privacySectionUse: "2. 利用目的",
    privacyUse1: "学習履歴・正答率・よく間違える問題の表示",
    privacyUse2: "言語と音声設定の保持",
    privacyUse3: "ユーザー体験の向上",
    privacySectionAds: "3. 第三者サービスとCookie",
    privacyAdsIntro: "広告配信のため Google AdSense を利用する場合があり、Google は広告配信の過程で Cookie を使用することがあります。",
    privacyGoogleAds: "Google 広告Cookieポリシー",
    privacyGooglePrivacy: "Google プライバシーポリシー",
    privacySectionDelete: "4. 保存期間と削除",
    privacyDelete1: "サイト内の「履歴削除」ボタンで削除できます。",
    privacyDelete2: "ブラウザのサイトデータ/Cookie削除機能でも削除できます。",
    privacySectionChild: "5. 子どもに関する案内",
    privacyChildBody: "本サイトは基礎学習コンテンツを提供する場合があります。保護者はネット利用と広告設定を一緒に確認してください。",
    privacySectionChange: "7. ポリシー変更",
    privacyChangeBody: "ポリシーが変更された場合は本ページでお知らせします。",
    privacyEffectiveDate: "施行日：2026-02-27",

    contactTitleTag: "お問い合わせ | 九九クイズ広場",
    contactMeta: "九九クイズ広場のお問い合わせページ",
    contactBadge: "サポート",
    contactH1: "お問い合わせ",
    contactLead: "使い方の不明点、バグ、ポリシーに関するお問い合わせは、以下の窓口からご連絡ください。",
    contactSectionChannel: "問い合わせ窓口",
    contactChannelBody: "お問い合わせは以下のメールアドレスで受け付けています。",
    contactSendEmail: "メールを送る",
    contactEmailLabel: "メール",
    contactResponse: "回答目安：営業日2〜3日以内。",
    contactSectionInfo: "確認を早めるための情報",
    contactInfo1: "問題画面のスクリーンショットまたは再現手順",
    contactInfo2: "利用端末/ブラウザ（例：iPhone Safari、Chrome）",
    contactInfo3: "発生した日時",
    contactInfo4: "そのときの設定（言語、段、モード、問題数など）",
    contactSectionScope: "対応範囲",
    contactScope1: "機能不具合・パフォーマンス問題",
    contactScope2: "広告表示に関する問い合わせ",
    contactScope3: "ポリシー・データ処理に関する問い合わせ",
  },

  es: {
    languageLabel: "Idioma",
    linkHome: "Inicio",
    linkAbout: "Acerca del sitio",
    linkPrivacy: "Política de privacidad",
    linkContact: "Contacto",
    linkQuizStart: "Iniciar quiz",
    linkGuide: "Guía de estudio",
    linkTerms: "Términos",

    aboutTitleTag: "Acerca del sitio | Parque de Quiz de Tablas",
    aboutMeta: "Página de información del Parque de Quiz de Tablas",
    aboutBadge: "Información del sitio",
    aboutH1: "Sobre el Parque de Quiz de Tablas",
    aboutLead: "Parque de Quiz de Tablas es un servicio web para practicar multiplicación básica de forma simple y entretenida.",
    aboutSectionOverview: "Resumen del servicio",
    aboutOverviewP1: "Permite practicar las tablas del 2 al 9 (hasta 20 si activas la extensión) y repetir según la configuración elegida.",
    aboutOverviewP2: "Ofrece retroalimentación de aprendizaje basada en precisión, errores frecuentes y velocidad en modo desafío.",
    aboutSectionOps: "Información operativa",
    aboutOps1: "Tipo de operación: sitio educativo operado por una persona",
    aboutOps2: "Tipo de servicio: contenido educativo gratuito",
    aboutOps3: "Registro de cuenta: no requerido",
    aboutOps4: "Última actualización: 2026-02-27",
    aboutSectionLinks: "Enlaces rápidos",

    privacyTitleTag: "Política de privacidad | Parque de Quiz de Tablas",
    privacyMeta: "Política de privacidad del Parque de Quiz de Tablas",
    privacyBadge: "Documento de política",
    privacyH1: "Política de privacidad",
    privacyLead: "Usamos solo los datos mínimos necesarios y el historial de estudio se guarda en tu navegador.",
    privacySectionStore: "1. Información recopilada/guardada",
    privacyStoreIntro: "El sitio puede usarse sin registro y no guarda en sus propios servidores datos personales directamente identificables (como nombre o correo).",
    privacyStore1: "Historial en localStorage: gugudan-history-v1",
    privacyStore2: "Preferencia de idioma: gugudan-language",
    privacyStore3: "Preferencia de voz TTS: gugudan-voice-*",
    privacySectionUse: "2. Finalidad de uso",
    privacyUse1: "Mostrar historial, precisión y preguntas falladas con frecuencia",
    privacyUse2: "Mantener idioma y voz seleccionados",
    privacyUse3: "Mejorar la experiencia de uso",
    privacySectionAds: "3. Servicios de terceros y cookies",
    privacyAdsIntro: "Este sitio puede usar Google AdSense para mostrar anuncios, y Google puede usar cookies durante la entrega de anuncios.",
    privacyGoogleAds: "Política de cookies de anuncios de Google",
    privacyGooglePrivacy: "Política de privacidad de Google",
    privacySectionDelete: "4. Conservación y eliminación",
    privacyDelete1: "Puedes borrar datos con el botón \"Borrar historial\" del sitio.",
    privacyDelete2: "También puedes borrarlos desde la configuración de datos/cookies del navegador.",
    privacySectionChild: "5. Aviso sobre menores",
    privacyChildBody: "Este sitio puede ofrecer contenido básico para menores. Los tutores deben revisar juntos el uso de internet y anuncios.",
    privacySectionChange: "7. Cambios de política",
    privacyChangeBody: "Si la política cambia, se anunciará en esta página.",
    privacyEffectiveDate: "Fecha de entrada en vigor: 2026-02-27",

    contactTitleTag: "Contacto | Parque de Quiz de Tablas",
    contactMeta: "Página de contacto del Parque de Quiz de Tablas",
    contactBadge: "Soporte",
    contactH1: "Contacto",
    contactLead: "Si tienes problemas de uso, errores o consultas de política, contáctanos por el canal de abajo.",
    contactSectionChannel: "Canal de contacto",
    contactChannelBody: "Las consultas se reciben en el correo electrónico siguiente.",
    contactSendEmail: "Enviar correo",
    contactEmailLabel: "Correo",
    contactResponse: "Tiempo objetivo de respuesta: 2-3 días hábiles.",
    contactSectionInfo: "Información útil para revisión rápida",
    contactInfo1: "Captura de pantalla o pasos para reproducir",
    contactInfo2: "Dispositivo/navegador usado (ej.: iPhone Safari, Chrome)",
    contactInfo3: "Fecha y hora del problema",
    contactInfo4: "Configuración seleccionada (idioma, tabla, modo, cantidad, etc.)",
    contactSectionScope: "Alcance de soporte",
    contactScope1: "Errores de funciones y rendimiento",
    contactScope2: "Consultas sobre visualización de anuncios",
    contactScope3: "Consultas sobre política y manejo de datos",
  },

  fr: {
    languageLabel: "Langue",
    linkHome: "Accueil",
    linkAbout: "À propos",
    linkPrivacy: "Politique de confidentialité",
    linkContact: "Contact",
    linkQuizStart: "Démarrer le quiz",
    linkGuide: "Guide d'apprentissage",
    linkTerms: "Conditions",

    aboutTitleTag: "À propos | Terrain de Quiz des Tables",
    aboutMeta: "Page de présentation du Terrain de Quiz des Tables",
    aboutBadge: "Infos du site",
    aboutH1: "À propos du Terrain de Quiz des Tables",
    aboutLead: "Terrain de Quiz des Tables est un service web pour s'entraîner au calcul de base de façon simple et ludique.",
    aboutSectionOverview: "Présentation du service",
    aboutOverviewP1: "Vous pouvez pratiquer les tables de 2 à 9 (jusqu'à 20 avec l'extension) et répéter selon les réglages choisis.",
    aboutOverviewP2: "Le site fournit des retours d'apprentissage selon la précision, les erreurs fréquentes et la vitesse en mode défi.",
    aboutSectionOps: "Informations d'exploitation",
    aboutOps1: "Type d'exploitation : site éducatif géré individuellement",
    aboutOps2: "Type de service : contenu éducatif gratuit",
    aboutOps3: "Inscription : non requise",
    aboutOps4: "Dernière mise à jour : 2026-02-27",
    aboutSectionLinks: "Liens rapides",

    privacyTitleTag: "Politique de confidentialité | Terrain de Quiz des Tables",
    privacyMeta: "Politique de confidentialité du Terrain de Quiz des Tables",
    privacyBadge: "Politique",
    privacyH1: "Politique de confidentialité",
    privacyLead: "Nous utilisons uniquement les données minimales nécessaires, et l'historique d'étude est stocké dans votre navigateur.",
    privacySectionStore: "1. Données collectées/enregistrées",
    privacyStoreIntro: "Le site s'utilise sans inscription et ne stocke pas sur ses propres serveurs de données personnelles directement identifiables (nom, e-mail, etc.).",
    privacyStore1: "Historique localStorage : gugudan-history-v1",
    privacyStore2: "Préférence de langue : gugudan-language",
    privacyStore3: "Préférence de voix TTS : gugudan-voice-*",
    privacySectionUse: "2. Finalités d'utilisation",
    privacyUse1: "Afficher l'historique, la précision et les questions souvent ratées",
    privacyUse2: "Conserver la langue et la voix choisies",
    privacyUse3: "Améliorer l'expérience utilisateur",
    privacySectionAds: "3. Services tiers et cookies",
    privacyAdsIntro: "Ce site peut utiliser Google AdSense pour la diffusion d'annonces, et Google peut utiliser des cookies dans ce cadre.",
    privacyGoogleAds: "Politique des cookies publicitaires Google",
    privacyGooglePrivacy: "Politique de confidentialité Google",
    privacySectionDelete: "4. Conservation et suppression",
    privacyDelete1: "Vous pouvez supprimer les données avec le bouton \"Effacer l'historique\" du site.",
    privacyDelete2: "Vous pouvez aussi supprimer via les paramètres de données/cookies du navigateur.",
    privacySectionChild: "5. Information relative aux enfants",
    privacyChildBody: "Ce site peut fournir du contenu éducatif de base. Les responsables légaux doivent vérifier l'utilisation d'internet et des annonces avec les enfants.",
    privacySectionChange: "7. Modifications de la politique",
    privacyChangeBody: "Toute modification sera annoncée sur cette page.",
    privacyEffectiveDate: "Date d'entrée en vigueur : 2026-02-27",

    contactTitleTag: "Contact | Terrain de Quiz des Tables",
    contactMeta: "Page de contact du Terrain de Quiz des Tables",
    contactBadge: "Support",
    contactH1: "Contact",
    contactLead: "Pour un problème d'utilisation, un bug ou une question de politique, contactez-nous via le canal ci-dessous.",
    contactSectionChannel: "Canal de contact",
    contactChannelBody: "Les demandes sont reçues à l'adresse e-mail ci-dessous.",
    contactSendEmail: "Envoyer un e-mail",
    contactEmailLabel: "E-mail",
    contactResponse: "Délai de réponse visé : 2 à 3 jours ouvrés.",
    contactSectionInfo: "Informations utiles pour vérification rapide",
    contactInfo1: "Capture d'écran ou étapes de reproduction",
    contactInfo2: "Appareil/navigateur utilisé (ex. iPhone Safari, Chrome)",
    contactInfo3: "Date et heure du problème",
    contactInfo4: "Réglages sélectionnés (langue, table, mode, nombre de questions, etc.)",
    contactSectionScope: "Périmètre de traitement",
    contactScope1: "Bugs fonctionnels et problèmes de performance",
    contactScope2: "Questions sur l'affichage des annonces",
    contactScope3: "Questions sur la politique et le traitement des données",
  },

  de: {
    languageLabel: "Sprache",
    linkHome: "Start",
    linkAbout: "Über die Website",
    linkPrivacy: "Datenschutz",
    linkContact: "Kontakt",
    linkQuizStart: "Quiz starten",
    linkGuide: "Lernleitfaden",
    linkTerms: "Bedingungen",

    aboutTitleTag: "Über die Website | Einmaleins-Quiz Spielplatz",
    aboutMeta: "Informationsseite des Einmaleins-Quiz Spielplatzes",
    aboutBadge: "Website-Info",
    aboutH1: "Über den Einmaleins-Quiz Spielplatz",
    aboutLead: "Der Einmaleins-Quiz Spielplatz ist ein webbasiertes Lernangebot, mit dem du das kleine Einmaleins einfach und mit Spaß üben kannst.",
    aboutSectionOverview: "Serviceüberblick",
    aboutOverviewP1: "Du kannst die Reihen von 2 bis 9 (mit Erweiterung bis 20) auswählen und beliebig oft wiederholen.",
    aboutOverviewP2: "Auf Basis von Trefferquote, häufig falschen Aufgaben und Antworttempo bekommst du hilfreiches Lernfeedback.",
    aboutSectionOps: "Betriebsinformationen",
    aboutOps1: "Betriebsart: privat betriebenes Lernangebot",
    aboutOps2: "Diensttyp: kostenlose Bildungsinhalte",
    aboutOps3: "Registrierung: nicht erforderlich",
    aboutOps4: "Zuletzt aktualisiert: 2026-02-27",
    aboutSectionLinks: "Schnellzugriffe",

    privacyTitleTag: "Datenschutz | Einmaleins-Quiz Spielplatz",
    privacyMeta: "Datenschutzerklärung des Einmaleins-Quiz Spielplatzes",
    privacyBadge: "Richtlinie",
    privacyH1: "Datenschutzerklärung",
    privacyLead: "Wir verarbeiten nur die nötigsten Daten; dein Lernverlauf bleibt in deinem Browser gespeichert.",
    privacySectionStore: "1. Welche Daten gespeichert werden",
    privacyStoreIntro: "Die Nutzung ist ohne Registrierung möglich. Direkt personenbezogene Daten wie Name oder E-Mail speichern wir nicht auf eigenen Servern.",
    privacyStore1: "Lernverlauf in localStorage: gugudan-history-v1",
    privacyStore2: "Spracheinstellung: gugudan-language",
    privacyStore3: "TTS-Stimmeinstellung: gugudan-voice-*",
    privacySectionUse: "2. Verwendungszweck",
    privacyUse1: "Anzeige von Lernverlauf, Genauigkeit und häufig falschen Aufgaben",
    privacyUse2: "Speichern der gewählten Sprach- und Stimmeinstellungen",
    privacyUse3: "Verbesserung der Benutzererfahrung",
    privacySectionAds: "3. Drittanbieter und Cookies",
    privacyAdsIntro: "Für Werbung kann diese Website Google AdSense nutzen. Google kann dabei Cookies verwenden.",
    privacyGoogleAds: "Google Ads Cookie-Richtlinie",
    privacyGooglePrivacy: "Google Datenschutzerklärung",
    privacySectionDelete: "4. Aufbewahrung und Löschung",
    privacyDelete1: "Daten können über die Schaltfläche \"Verlauf löschen\" gelöscht werden.",
    privacyDelete2: "Alternativ über Browser-Einstellungen für Website-Daten/Cookies.",
    privacySectionChild: "5. Hinweis zu Kindern",
    privacyChildBody: "Diese Website kann grundlegende Lerninhalte für Kinder bereitstellen. Erziehungsberechtigte sollten Internet- und Anzeigeneinstellungen gemeinsam prüfen.",
    privacySectionChange: "7. Änderungen der Richtlinie",
    privacyChangeBody: "Änderungen werden auf dieser Seite bekannt gegeben.",
    privacyEffectiveDate: "Gültig ab: 2026-02-27",

    contactTitleTag: "Kontakt | Einmaleins-Quiz Spielplatz",
    contactMeta: "Kontaktseite des Einmaleins-Quiz Spielplatzes",
    contactBadge: "Support",
    contactH1: "Kontakt",
    contactLead: "Bei Fragen zur Nutzung, bei Bugs oder Richtlinien-Themen erreichst du uns über den folgenden Kanal.",
    contactSectionChannel: "Kontaktkanal",
    contactChannelBody: "Anfragen nehmen wir per E-Mail unter der folgenden Adresse entgegen.",
    contactSendEmail: "E-Mail senden",
    contactEmailLabel: "E-Mail",
    contactResponse: "Wir antworten in der Regel innerhalb von 2-3 Werktagen.",
    contactSectionInfo: "Hilfreiche Angaben",
    contactInfo1: "Screenshot oder Schritte zur Reproduktion",
    contactInfo2: "Verwendetes Gerät/Browser (z. B. iPhone Safari, Chrome)",
    contactInfo3: "Datum und Uhrzeit des Problems",
    contactInfo4: "Gewählte Einstellungen (Sprache, Reihe, Modus, Anzahl Fragen usw.)",
    contactSectionScope: "Bearbeitungsbereich",
    contactScope1: "Funktionsfehler und Leistungsprobleme",
    contactScope2: "Fragen zur Anzeigenanzeige",
    contactScope3: "Fragen zu Richtlinien und Datenverarbeitung",
  },

  pt: {
    languageLabel: "Idioma",
    linkHome: "Início",
    linkAbout: "Sobre o site",
    linkPrivacy: "Política de privacidade",
    linkContact: "Contato",
    linkQuizStart: "Iniciar quiz",
    linkGuide: "Guia de estudo",
    linkTerms: "Termos",

    aboutTitleTag: "Sobre o site | Parque de Quiz da Tabuada",
    aboutMeta: "Página de apresentação do Parque de Quiz da Tabuada",
    aboutBadge: "Informações do site",
    aboutH1: "Sobre o Parque de Quiz da Tabuada",
    aboutLead: "O Parque de Quiz da Tabuada é um serviço de aprendizagem na web para praticar multiplicação básica de forma simples e divertida.",
    aboutSectionOverview: "Visão geral",
    aboutOverviewP1: "Você pode praticar as tabuadas de 2 a 9 (ou até 20 com a extensão) e repetir quantas vezes quiser.",
    aboutOverviewP2: "Com base na sua precisão, nos erros mais frequentes e na velocidade de resposta, o site oferece feedback para apoiar o estudo.",
    aboutSectionOps: "Informações de operação",
    aboutOps1: "Tipo de operação: site educacional operado individualmente",
    aboutOps2: "Tipo de serviço: conteúdo educacional gratuito",
    aboutOps3: "Cadastro: não necessário",
    aboutOps4: "Última atualização: 2026-02-27",
    aboutSectionLinks: "Links rápidos",

    privacyTitleTag: "Política de privacidade | Parque de Quiz da Tabuada",
    privacyMeta: "Política de privacidade do Parque de Quiz da Tabuada",
    privacyBadge: "Política",
    privacyH1: "Política de privacidade",
    privacyLead: "Usamos apenas os dados estritamente necessários, e o histórico de estudo fica armazenado no seu navegador.",
    privacySectionStore: "1. Dados coletados/armazenados",
    privacyStoreIntro: "Você pode usar o site sem cadastro. Não armazenamos em servidores próprios dados pessoais que identifiquem diretamente a pessoa (como nome ou e-mail).",
    privacyStore1: "Histórico no localStorage: gugudan-history-v1",
    privacyStore2: "Preferência de idioma: gugudan-language",
    privacyStore3: "Preferência de voz TTS: gugudan-voice-*",
    privacySectionUse: "2. Finalidade de uso",
    privacyUse1: "Exibir histórico, precisão e questões com erro frequente",
    privacyUse2: "Manter idioma e voz selecionados",
    privacyUse3: "Melhorar a experiência do usuário",
    privacySectionAds: "3. Serviços de terceiros e cookies",
    privacyAdsIntro: "Este site pode usar o Google AdSense para exibir anúncios, e o Google pode utilizar cookies nesse processo.",
    privacyGoogleAds: "Política de cookies de anúncios do Google",
    privacyGooglePrivacy: "Política de privacidade do Google",
    privacySectionDelete: "4. Retenção e exclusão",
    privacyDelete1: "Você pode apagar os dados pelo botão \"Limpar histórico\" no site.",
    privacyDelete2: "Também pode apagar nas configurações de dados/cookies do navegador.",
    privacySectionChild: "5. Aviso sobre crianças",
    privacyChildBody: "Este site pode oferecer conteúdo básico para crianças. Responsáveis devem revisar uso da internet e anúncios junto com elas.",
    privacySectionChange: "7. Mudanças na política",
    privacyChangeBody: "Se a política mudar, a atualização será publicada nesta página.",
    privacyEffectiveDate: "Data de vigência: 2026-02-27",

    contactTitleTag: "Contato | Parque de Quiz da Tabuada",
    contactMeta: "Página de contato do Parque de Quiz da Tabuada",
    contactBadge: "Suporte",
    contactH1: "Contato",
    contactLead: "Se tiver dificuldade de uso, encontrar um bug ou tiver dúvida sobre políticas, fale com a gente pelo canal abaixo.",
    contactSectionChannel: "Canal de contato",
    contactChannelBody: "Atendemos solicitações pelo e-mail abaixo.",
    contactSendEmail: "Enviar e-mail",
    contactEmailLabel: "E-mail",
    contactResponse: "Nosso prazo de resposta é, em geral, de 2 a 3 dias úteis.",
    contactSectionInfo: "Informações que ajudam na análise",
    contactInfo1: "Captura de tela ou passos para reproduzir",
    contactInfo2: "Dispositivo/navegador usado (ex.: iPhone Safari, Chrome)",
    contactInfo3: "Data e hora do problema",
    contactInfo4: "Configurações escolhidas (idioma, tabuada, modo, quantidade de questões etc.)",
    contactSectionScope: "Escopo de atendimento",
    contactScope1: "Falhas de função e desempenho",
    contactScope2: "Dúvidas sobre exibição de anúncios",
    contactScope3: "Dúvidas sobre política e tratamento de dados",
  },

  vi: {
    languageLabel: "Ngôn ngữ",
    linkHome: "Trang chủ",
    linkAbout: "Giới thiệu trang",
    linkPrivacy: "Chính sách riêng tư",
    linkContact: "Liên hệ",
    linkQuizStart: "Bắt đầu quiz",
    linkGuide: "Hướng dẫn học",
    linkTerms: "Điều khoản",

    aboutTitleTag: "Giới thiệu | Sân chơi Quiz Cửu Chương",
    aboutMeta: "Trang giới thiệu Sân chơi Quiz Cửu Chương",
    aboutBadge: "Thông tin trang",
    aboutH1: "Giới thiệu Sân chơi Quiz Cửu Chương",
    aboutLead: "Sân chơi Quiz Cửu Chương là dịch vụ học tập trên web giúp bạn luyện phép nhân cơ bản theo cách dễ hiểu và thú vị.",
    aboutSectionOverview: "Tổng quan dịch vụ",
    aboutOverviewP1: "Bạn có thể luyện bảng nhân từ 2 đến 9 (mở rộng đến 20 khi bật) và ôn lại nhiều lần theo nhu cầu.",
    aboutOverviewP2: "Trang sẽ đưa ra phản hồi học tập dựa trên độ chính xác, các câu hay sai và tốc độ trả lời.",
    aboutSectionOps: "Thông tin vận hành",
    aboutOps1: "Hình thức vận hành: trang học tập do cá nhân vận hành",
    aboutOps2: "Loại dịch vụ: nội dung giáo dục miễn phí",
    aboutOps3: "Đăng ký tài khoản: không cần",
    aboutOps4: "Cập nhật lần cuối: 2026-02-27",
    aboutSectionLinks: "Liên kết nhanh",

    privacyTitleTag: "Chính sách riêng tư | Sân chơi Quiz Cửu Chương",
    privacyMeta: "Chính sách riêng tư của Sân chơi Quiz Cửu Chương",
    privacyBadge: "Tài liệu chính sách",
    privacyH1: "Chính sách riêng tư",
    privacyLead: "Chúng tôi chỉ sử dụng lượng dữ liệu tối thiểu cần thiết; lịch sử học được lưu trong trình duyệt của bạn.",
    privacySectionStore: "1. Dữ liệu được thu thập/lưu",
    privacyStoreIntro: "Bạn có thể dùng trang web mà không cần đăng ký. Chúng tôi không lưu trên máy chủ riêng các thông tin cá nhân có thể nhận diện trực tiếp (như tên hoặc email).",
    privacyStore1: "Lịch sử học trong localStorage: gugudan-history-v1",
    privacyStore2: "Cài đặt ngôn ngữ: gugudan-language",
    privacyStore3: "Cài đặt giọng TTS: gugudan-voice-*",
    privacySectionUse: "2. Mục đích sử dụng",
    privacyUse1: "Hiển thị lịch sử học, độ chính xác và câu hay sai",
    privacyUse2: "Giữ cài đặt ngôn ngữ và giọng đọc",
    privacyUse3: "Cải thiện trải nghiệm người dùng",
    privacySectionAds: "3. Dịch vụ bên thứ ba và cookie",
    privacyAdsIntro: "Trang web có thể sử dụng Google AdSense để hiển thị quảng cáo; Google có thể dùng cookie trong quá trình này.",
    privacyGoogleAds: "Chính sách cookie quảng cáo Google",
    privacyGooglePrivacy: "Chính sách riêng tư Google",
    privacySectionDelete: "4. Thời gian lưu và xóa",
    privacyDelete1: "Bạn có thể xóa dữ liệu bằng nút \"Xóa lịch sử\" trên trang.",
    privacyDelete2: "Bạn cũng có thể xóa trong cài đặt dữ liệu/cookie của trình duyệt.",
    privacySectionChild: "5. Lưu ý về trẻ em",
    privacyChildBody: "Trang web có thể cung cấp nội dung học cơ bản cho trẻ em. Phụ huynh nên cùng trẻ kiểm tra việc sử dụng internet và quảng cáo.",
    privacySectionChange: "7. Thay đổi chính sách",
    privacyChangeBody: "Mọi thay đổi sẽ được thông báo trên trang này.",
    privacyEffectiveDate: "Ngày hiệu lực: 2026-02-27",

    contactTitleTag: "Liên hệ | Sân chơi Quiz Cửu Chương",
    contactMeta: "Trang liên hệ của Sân chơi Quiz Cửu Chương",
    contactBadge: "Hỗ trợ",
    contactH1: "Liên hệ",
    contactLead: "Nếu gặp lỗi, khó khăn khi sử dụng hoặc có câu hỏi về chính sách, vui lòng liên hệ qua kênh bên dưới.",
    contactSectionChannel: "Kênh liên hệ",
    contactChannelBody: "Chúng tôi tiếp nhận yêu cầu hỗ trợ qua địa chỉ email dưới đây.",
    contactSendEmail: "Gửi email",
    contactEmailLabel: "Email",
    contactResponse: "Mục tiêu phản hồi: trong vòng 2-3 ngày làm việc.",
    contactSectionInfo: "Thông tin giúp xử lý nhanh",
    contactInfo1: "Ảnh chụp màn hình hoặc bước tái hiện lỗi",
    contactInfo2: "Thiết bị/trình duyệt sử dụng (ví dụ: iPhone Safari, Chrome)",
    contactInfo3: "Ngày và giờ xảy ra vấn đề",
    contactInfo4: "Thiết lập đã chọn (ngôn ngữ, bảng nhân, chế độ, số câu hỏi, v.v.)",
    contactSectionScope: "Phạm vi hỗ trợ",
    contactScope1: "Lỗi tính năng và hiệu năng",
    contactScope2: "Câu hỏi về hiển thị quảng cáo",
    contactScope3: "Câu hỏi về chính sách và xử lý dữ liệu",
  },

  th: {
    languageLabel: "ภาษา",
    linkHome: "หน้าแรก",
    linkAbout: "เกี่ยวกับเว็บไซต์",
    linkPrivacy: "นโยบายความเป็นส่วนตัว",
    linkContact: "ติดต่อ",
    linkQuizStart: "เริ่มควิซ",
    linkGuide: "คู่มือการเรียนรู้",
    linkTerms: "ข้อกำหนด",

    aboutTitleTag: "เกี่ยวกับเว็บไซต์ | สนามเด็กเล่นควิซตารางคูณ",
    aboutMeta: "หน้าแนะนำบริการสนามเด็กเล่นควิซตารางคูณ",
    aboutBadge: "ข้อมูลเว็บไซต์",
    aboutH1: "เกี่ยวกับสนามเด็กเล่นควิซตารางคูณ",
    aboutLead: "สนามเด็กเล่นควิซตารางคูณเป็นบริการเรียนรู้บนเว็บที่ช่วยให้ฝึกการคูณพื้นฐานได้ง่ายและสนุกขึ้น",
    aboutSectionOverview: "ภาพรวมบริการ",
    aboutOverviewP1: "คุณสามารถฝึกตารางคูณ 2-9 (ขยายได้ถึง 20 เมื่อเปิดใช้งาน) และทบทวนซ้ำได้ตามต้องการ",
    aboutOverviewP2: "ระบบจะแสดงคำแนะนำการเรียนรู้จากความแม่นยำ ข้อที่ผิดบ่อย และความเร็วในการตอบ",
    aboutSectionOps: "ข้อมูลการดำเนินงาน",
    aboutOps1: "รูปแบบการดำเนินงาน: เว็บไซต์การเรียนรู้ที่ดูแลโดยบุคคล",
    aboutOps2: "ประเภทบริการ: เนื้อหาการศึกษาฟรี",
    aboutOps3: "การสมัครสมาชิก: ไม่จำเป็น",
    aboutOps4: "อัปเดตล่าสุด: 2026-02-27",
    aboutSectionLinks: "ลิงก์ด่วน",

    privacyTitleTag: "นโยบายความเป็นส่วนตัว | สนามเด็กเล่นควิซตารางคูณ",
    privacyMeta: "นโยบายความเป็นส่วนตัวของสนามเด็กเล่นควิซตารางคูณ",
    privacyBadge: "เอกสารนโยบาย",
    privacyH1: "นโยบายความเป็นส่วนตัว",
    privacyLead: "เราใช้ข้อมูลเท่าที่จำเป็นเท่านั้น และบันทึกประวัติการเรียนไว้ในเบราว์เซอร์ของคุณ",
    privacySectionStore: "1. ข้อมูลที่เก็บ",
    privacyStoreIntro: "เว็บไซต์นี้ใช้งานได้โดยไม่ต้องสมัครสมาชิก และเราไม่เก็บข้อมูลส่วนบุคคลที่ระบุตัวตนได้โดยตรง (เช่น ชื่อหรืออีเมล) ไว้บนเซิร์ฟเวอร์ของเรา",
    privacyStore1: "ประวัติการเรียนใน localStorage: gugudan-history-v1",
    privacyStore2: "การตั้งค่าภาษา: gugudan-language",
    privacyStore3: "การตั้งค่าเสียง TTS: gugudan-voice-*",
    privacySectionUse: "2. วัตถุประสงค์การใช้งาน",
    privacyUse1: "แสดงประวัติการเรียน ความแม่นยำ และข้อที่ผิดบ่อย",
    privacyUse2: "จดจำการตั้งค่าภาษาและเสียง",
    privacyUse3: "ปรับปรุงประสบการณ์การใช้งาน",
    privacySectionAds: "3. บริการบุคคลที่สามและคุกกี้",
    privacyAdsIntro: "เว็บไซต์นี้อาจใช้ Google AdSense เพื่อแสดงโฆษณา และ Google อาจใช้คุกกี้ในกระบวนการดังกล่าว",
    privacyGoogleAds: "นโยบายคุกกี้โฆษณา Google",
    privacyGooglePrivacy: "นโยบายความเป็นส่วนตัวของ Google",
    privacySectionDelete: "4. ระยะเวลาจัดเก็บและการลบ",
    privacyDelete1: "คุณสามารถลบข้อมูลด้วยปุ่ม \"ล้างประวัติ\" บนเว็บไซต์",
    privacyDelete2: "หรือจะลบผ่านการตั้งค่าข้อมูลเว็บไซต์/คุกกี้ของเบราว์เซอร์ก็ได้",
    privacySectionChild: "5. ข้อแนะนำเกี่ยวกับเด็ก",
    privacyChildBody: "เว็บไซต์นี้อาจมีเนื้อหาการเรียนพื้นฐานสำหรับเด็ก ผู้ปกครองควรตรวจสอบการใช้อินเทอร์เน็ตและโฆษณาร่วมกับเด็ก",
    privacySectionChange: "7. การเปลี่ยนนโยบาย",
    privacyChangeBody: "หากมีการเปลี่ยนแปลง จะประกาศในหน้านี้",
    privacyEffectiveDate: "วันที่มีผลบังคับใช้: 2026-02-27",

    contactTitleTag: "ติดต่อ | สนามเด็กเล่นควิซตารางคูณ",
    contactMeta: "หน้าติดต่อสนามเด็กเล่นควิซตารางคูณ",
    contactBadge: "สนับสนุน",
    contactH1: "ติดต่อ",
    contactLead: "หากพบปัญหาการใช้งาน บั๊ก หรือมีคำถามด้านนโยบาย โปรดติดต่อผ่านช่องทางด้านล่าง",
    contactSectionChannel: "ช่องทางติดต่อ",
    contactChannelBody: "เรารับเรื่องติดต่อผ่านอีเมลด้านล่าง",
    contactSendEmail: "ส่งอีเมล",
    contactEmailLabel: "อีเมล",
    contactResponse: "โดยทั่วไปเราตอบกลับภายใน 2-3 วันทำการ",
    contactSectionInfo: "ข้อมูลที่ช่วยให้ตรวจสอบได้เร็ว",
    contactInfo1: "ภาพหน้าจอหรือขั้นตอนการเกิดปัญหา",
    contactInfo2: "อุปกรณ์/เบราว์เซอร์ที่ใช้ (เช่น iPhone Safari, Chrome)",
    contactInfo3: "วันที่และเวลาที่เกิดปัญหา",
    contactInfo4: "การตั้งค่าที่เลือก (ภาษา ตารางคูณ โหมด จำนวนข้อ ฯลฯ)",
    contactSectionScope: "ขอบเขตการรองรับ",
    contactScope1: "ปัญหาฟังก์ชันและประสิทธิภาพ",
    contactScope2: "คำถามเกี่ยวกับการแสดงโฆษณา",
    contactScope3: "คำถามด้านนโยบายและการจัดการข้อมูล",
  },

  id: {
    languageLabel: "Bahasa",
    linkHome: "Beranda",
    linkAbout: "Tentang situs",
    linkPrivacy: "Kebijakan privasi",
    linkContact: "Kontak",
    linkQuizStart: "Mulai kuis",
    linkGuide: "Panduan belajar",
    linkTerms: "Ketentuan",

    aboutTitleTag: "Tentang Situs | Taman Kuis Perkalian",
    aboutMeta: "Halaman informasi Taman Kuis Perkalian",
    aboutBadge: "Info situs",
    aboutH1: "Tentang Taman Kuis Perkalian",
    aboutLead: "Taman Kuis Perkalian adalah layanan belajar berbasis web yang membantu Anda melatih perkalian dasar dengan cara yang sederhana dan menyenangkan.",
    aboutSectionOverview: "Ringkasan layanan",
    aboutOverviewP1: "Anda bisa berlatih tabel perkalian 2-9 (hingga 20 saat ekstensi diaktifkan) dan mengulangnya sesering yang dibutuhkan.",
    aboutOverviewP2: "Situs memberikan umpan balik belajar berdasarkan akurasi, soal yang sering keliru, dan kecepatan menjawab.",
    aboutSectionOps: "Informasi operasional",
    aboutOps1: "Jenis operasional: situs belajar dikelola secara individu",
    aboutOps2: "Jenis layanan: konten pendidikan gratis",
    aboutOps3: "Pendaftaran akun: tidak diperlukan",
    aboutOps4: "Pembaruan terakhir: 2026-02-27",
    aboutSectionLinks: "Tautan cepat",

    privacyTitleTag: "Kebijakan Privasi | Taman Kuis Perkalian",
    privacyMeta: "Kebijakan privasi Taman Kuis Perkalian",
    privacyBadge: "Dokumen kebijakan",
    privacyH1: "Kebijakan Privasi",
    privacyLead: "Kami hanya menggunakan data minimum yang benar-benar diperlukan, dan riwayat belajar disimpan di browser Anda.",
    privacySectionStore: "1. Data yang dikumpulkan/disimpan",
    privacyStoreIntro: "Situs ini dapat digunakan tanpa pendaftaran. Kami tidak menyimpan data pribadi yang dapat mengidentifikasi langsung (seperti nama atau email) di server kami.",
    privacyStore1: "Riwayat belajar di localStorage: gugudan-history-v1",
    privacyStore2: "Preferensi bahasa: gugudan-language",
    privacyStore3: "Preferensi suara TTS: gugudan-voice-*",
    privacySectionUse: "2. Tujuan penggunaan",
    privacyUse1: "Menampilkan riwayat belajar, akurasi, dan soal yang sering salah",
    privacyUse2: "Menyimpan pengaturan bahasa dan suara",
    privacyUse3: "Meningkatkan pengalaman pengguna",
    privacySectionAds: "3. Layanan pihak ketiga dan cookie",
    privacyAdsIntro: "Situs ini dapat menggunakan Google AdSense untuk menayangkan iklan, dan Google dapat menggunakan cookie dalam proses tersebut.",
    privacyGoogleAds: "Kebijakan cookie iklan Google",
    privacyGooglePrivacy: "Kebijakan privasi Google",
    privacySectionDelete: "4. Retensi dan penghapusan",
    privacyDelete1: "Data dapat dihapus dengan tombol \"Hapus riwayat\" di situs.",
    privacyDelete2: "Data juga dapat dihapus melalui pengaturan data situs/cookie pada browser.",
    privacySectionChild: "5. Pemberitahuan terkait anak",
    privacyChildBody: "Situs ini dapat menyediakan konten belajar dasar untuk anak. Wali dianjurkan meninjau penggunaan internet dan iklan bersama anak.",
    privacySectionChange: "7. Perubahan kebijakan",
    privacyChangeBody: "Jika ada perubahan kebijakan, akan diumumkan di halaman ini.",
    privacyEffectiveDate: "Tanggal berlaku: 2026-02-27",

    contactTitleTag: "Kontak | Taman Kuis Perkalian",
    contactMeta: "Halaman kontak Taman Kuis Perkalian",
    contactBadge: "Dukungan",
    contactH1: "Kontak",
    contactLead: "Jika Anda mengalami kendala penggunaan, menemukan bug, atau punya pertanyaan kebijakan, silakan hubungi melalui saluran di bawah.",
    contactSectionChannel: "Saluran kontak",
    contactChannelBody: "Pertanyaan kami terima melalui alamat email di bawah ini.",
    contactSendEmail: "Kirim email",
    contactEmailLabel: "Email",
    contactResponse: "Target waktu respons kami adalah dalam 2-3 hari kerja.",
    contactSectionInfo: "Informasi yang membantu pemeriksaan cepat",
    contactInfo1: "Tangkapan layar atau langkah reproduksi masalah",
    contactInfo2: "Perangkat/browser yang digunakan (contoh: iPhone Safari, Chrome)",
    contactInfo3: "Tanggal dan waktu kejadian",
    contactInfo4: "Pengaturan yang dipilih (bahasa, tabel, mode, jumlah soal, dll.)",
    contactSectionScope: "Cakupan penanganan",
    contactScope1: "Bug fitur dan masalah performa",
    contactScope2: "Pertanyaan terkait tampilan iklan",
    contactScope3: "Pertanyaan kebijakan dan pengelolaan data",
  },
};

const state = {
  lang: "ko",
};

function t(key) {
  const pack = I18N[state.lang] || I18N.ko;
  return pack[key] ?? I18N.en[key] ?? I18N.ko[key] ?? key;
}

function applyTranslations() {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.dataset.i18n;
    el.textContent = t(key);
  });

  document.querySelectorAll("[data-i18n-meta]").forEach((el) => {
    const key = el.dataset.i18nMeta;
    el.setAttribute("content", t(key));
  });

  const titleKeyMap = {
    about: "aboutTitleTag",
    privacy: "privacyTitleTag",
    contact: "contactTitleTag",
    guide: "guideTitleTag",
    terms: "termsTitleTag",
  };

  const titleKey = titleKeyMap[page];
  if (titleKey) {
    document.title = t(titleKey);
  }

  document.documentElement.lang = state.lang;
}

function initLanguage() {
  const saved = localStorage.getItem(LANG_KEY);
  state.lang = I18N[saved] ? saved : "ko";
  if (legalLanguageSelect) {
    legalLanguageSelect.value = state.lang;
    legalLanguageSelect.addEventListener("change", () => {
      const next = legalLanguageSelect.value;
      state.lang = I18N[next] ? next : "ko";
      localStorage.setItem(LANG_KEY, state.lang);
      applyTranslations();
    });
  }
}

initLanguage();
applyTranslations();
